package co.org.softsolut.conozcapacho.ejb.persistencia.entidades;

// Generated 26/10/2013 08:11:24 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Simbolos generated by hbm2java
 */
@Entity
@Table(name = "simbolos")
public class Simbolos implements java.io.Serializable {

	private int simCodigo;
	private byte[] simImagen;
	private String simDescripcion;

	public Simbolos() {
	}

	public Simbolos(int simCodigo, byte[] simImagen, String simDescripcion) {
		this.simCodigo = simCodigo;
		this.simImagen = simImagen;
		this.simDescripcion = simDescripcion;
	}

	@Id
	@Column(name = "sim_codigo", unique = true, nullable = false)
	public int getSimCodigo() {
		return this.simCodigo;
	}

	public void setSimCodigo(int simCodigo) {
		this.simCodigo = simCodigo;
	}

	@Column(name = "sim_imagen", nullable = false)
	public byte[] getSimImagen() {
		return this.simImagen;
	}

	public void setSimImagen(byte[] simImagen) {
		this.simImagen = simImagen;
	}

	@Column(name = "sim_descripcion", nullable = false)
	public String getSimDescripcion() {
		return this.simDescripcion;
	}

	public void setSimDescripcion(String simDescripcion) {
		this.simDescripcion = simDescripcion;
	}

}
